export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const UPDATE_USERNAME_ERR = 'UPDATE_USERNAME_ERR';
export const UPDATE_PASSWORD_ERR = 'UPDATE_PASSWORD_ERR';

export const SELECT_USER = 'SELECT_USER';
